[package]
name = "rplace-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true


[dependencies]
chrono = "0.4.19"
tracy-client = "0.12.7"
image = "0.24.1"